import { writeFileSync } from 'node:fs';
import { coreServiceCatalog, type ServiceDefinition } from '@aar/shared';
import { PATHS, PINS, categoryForResourceType, type Pin } from './config.js';
import { buildIconIndex, resolveIcon } from './icons.js';
import { fetchAvmModules, fetchPopularity, resolveResourceType, type RawModule } from './sources.js';

interface Candidate {
  def: ServiceDefinition;
  resourceType: string;
  pinned: boolean;
  droppedNoIcon?: boolean;
}

function titleCase(kebab: string): string {
  return kebab.split('-').map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

function pinToCandidate(pin: Pin, icon: string): Candidate {
  const def: ServiceDefinition = {
    id: pin.id,
    name: pin.name,
    category: pin.category,
    description: pin.description ?? '',
    icon,
    defaults: {},
    iac: { resourceType: pin.resourceType, avmModule: pin.avmModule },
    draft: true,
    ...(pin.pricing ? { pricing: { consumptionBased: false, ...pin.pricing } } : {}),
    ...(pin.docsUrl ? { docsUrl: pin.docsUrl } : {}),
  };
  return { def, resourceType: pin.resourceType, pinned: true };
}

async function main(): Promise<void> {
  const iconIndex = buildIconIndex();
  const taken = new Set(coreServiceCatalog.map((s) => s.id));
  const takenTypes = new Set(
    coreServiceCatalog.map((s) => s.iac?.resourceType?.toLowerCase()).filter((t): t is string => Boolean(t)),
  );
  const candidates: Candidate[] = [];
  const dropped: string[] = [];

  // Pins are always attempted first.
  for (const pin of PINS) {
    if (taken.has(pin.id) || takenTypes.has(pin.resourceType.toLowerCase())) continue;
    const icon = resolveIcon(iconIndex, { resourceType: pin.resourceType, name: pin.name, preferred: pin.icon });
    if (!icon) {
      dropped.push(`${pin.name} (pinned — no icon on disk: ${pin.icon})`);
      continue;
    }
    candidates.push(pinToCandidate(pin, icon));
    taken.add(pin.id);
    takenTypes.add(pin.resourceType.toLowerCase());
  }

  // Live AVM modules (best-effort; empty offline).
  const modules = await fetchAvmModules();
  console.log(`  Found ${modules.length} AVM resource modules.`);
  for (const mod of modules) {
    const id = mod.name;
    if (taken.has(id)) continue;
    const resourceType = mod.resourceType ?? (await resolveResourceType(mod));
    if (!resourceType || takenTypes.has(resourceType.toLowerCase())) continue;
    const name = titleCase(mod.name);
    const icon = resolveIcon(iconIndex, { resourceType, name });
    if (!icon) {
      dropped.push(`${name} (${resourceType}) — no official icon`);
      continue;
    }
    candidates.push({
      def: {
        id,
        name,
        category: categoryForResourceType(resourceType),
        description: '',
        icon,
        defaults: {},
        iac: { resourceType, avmModule: mod.avmModule },
        draft: true,
      },
      resourceType,
      pinned: false,
    });
    taken.add(id);
    takenTypes.add(resourceType.toLowerCase());
  }

  // Popularity for ordering + a "popular" badge (best-effort).
  const scores = await fetchPopularity(candidates.map((c) => c.resourceType));
  for (const c of candidates) {
    const score = scores.get(c.resourceType);
    if (typeof score === 'number') c.def.popularityScore = score;
  }
  candidates.sort(
    (a, b) => (b.def.popularityScore ?? 0) - (a.def.popularityScore ?? 0) || a.def.name.localeCompare(b.def.name),
  );

  writeGenerated(candidates.map((c) => c.def));
  printSummary(candidates, dropped);
}

function writeGenerated(defs: ServiceDefinition[]): void {
  const body = `// AUTO-GENERATED by tools/catalog-sync — do not edit by hand.
// Draft service candidates detected from Azure Verified Modules + official icons.
// Promote an entry into the core catalog (catalog.ts) after filling defaults and
// cost/resiliency/throughput models, then remove it here.
/* eslint-disable */
import type { ServiceDefinition } from './catalog.js';

export const generatedServiceCatalog: ServiceDefinition[] = ${JSON.stringify(defs, null, 2)};
`;
  writeFileSync(PATHS.generatedCatalog, body);
}

function printSummary(candidates: Candidate[], dropped: string[]): void {
  console.log(`\nGenerated ${candidates.length} draft candidate(s):`);
  for (const c of candidates) {
    const score = c.def.popularityScore ?? '—';
    console.log(`  ${c.pinned ? '📌' : '  '} ${c.def.id.padEnd(28)} ${c.def.category.padEnd(11)} pop=${score}`);
  }
  if (dropped.length) {
    console.log(`\nSkipped ${dropped.length} (no icon / already present):`);
    for (const d of dropped) console.log(`  - ${d}`);
  }
  console.log(
    '\nEach draft still needs curation before promotion: defaults, and COST_MODEL / ' +
      'SERVICE_RESILIENCE / SERVICE_THROUGHPUT entries keyed by id.',
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
